version: "2.4"
services:
  web:
    image: nginx:latest
    ports:
        - "127.0.0.1:80:80"
    volumes:
        - ./tutorials:/usr/share/nginx/html/
        - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
  php:
    image: php:7-fpm
    volumes:
        - ./tutorials:/usr/share/nginx/html/
